# Coupons
type Coupon {
  name: String!
  code: String!
  discount: Int!
  expiresOn: Int!
}

input NewCouponInput {
  name: String!
  code: String!
  discount: Int!
  expiresOn: Int!
}

input UpdateCouponInput {
  name: String
  code: String
  discount: Int
  expiresOn: Int
}

extend type Query {
  coupons: [Coupon]!
  coupon: Coupon!
}

extend type Mutation {
  newCoupon(input: NewCouponInput!): Coupon!
  updateCoupon(input: UpdateCouponInput!): Coupon!
  removeCoupon(id: ID!): Coupon!
}
